---
abstract: ~
author: '-2006, Sean M. Burke C<sburke@netadventure.net>, all rights'
build_requires:
  Pod::Coverage: 0.18
  Test::Pod: 1.26
  Test::Pod::Coverage: 1.08
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Games-Worms
no_index:
  directory:
    - inc
    - t
recommends:
  Tk: 0
version: 0.65
